packages/personal/eslint-plugin/package.json, packages/personal/prettier-config/package.json, packages/public/prettier-plugin-jsdoc/package.json, yarn.lock
The reason the `publishConfig` was added and the repository property format was changed is because the Yarn website wasn't showing the packages, and I believe this may be the reason.
There's no actual change to the code, but you can always...
```bash
npm test
yarn test
```
=> Add publishConfig and fix the repository property format

packages/public/prettier-plugin-jsdoc/src/fns/getParsers.js
Prevent crash in Jest
Somehow get Jest to run prettier :) I don't know why it does it, but it crashes here and this makes it work.
=> createParser: guard against missing options

.gitignore, .husky/commit-msg, .husky/post-merge, .husky/pre-commit, CONTRIBUTING.md, package.json, packages/personal/eslint-plugin/package.json, utils/hooks/commit-msg, utils/hooks/post-merge, utils/hooks/pre-commit, utils/scripts/prepare, yarn.lock
- It updates all the dependencies to their latest version... except for `comment-parser`, as I couldn't find a commit nor a tag referencing the published version, and being a production dependency, I don't feel comfortable installing it like that.
- It adds a small `CONTRIBUTING.md` with the basic rules for PRs.
```bash
npm test
yarn test
```
=> Update dependencies and add a CONTRIBUTING.md

package.json, packages/personal/eslint-plugin/package.json, packages/public/prettier-plugin-jsdoc/package.json, packages/public/prettier-plugin-jsdoc/src/fns/app.js, packages/public/prettier-plugin-jsdoc/src/fns/formatStringLiterals.js, packages/public/prettier-plugin-jsdoc/test/e2e/fixtures/random-03.fixture.js, packages/public/prettier-plugin-jsdoc/test/unit/fns/prepareTagDescription.test.js, packages/public/prettier-plugin-jsdoc/test/unit/fns/render.test.js, yarn.lock
- Updates all the dependencies to their latest versions.
- Fixes a regexp that was causing #15, and adds a fixture of the use case.
```bash
npm test
yarn test
```
=> Update dependencies and fix #15

README.md, package.json, packages/personal/eslint-plugin/package.json, packages/personal/eslint-plugin/rules/jsdoc.js, packages/public/prettier-plugin-jsdoc/README.md, packages/public/prettier-plugin-jsdoc/package.json, packages/public/prettier-plugin-jsdoc/src/fns/getOptions.js, packages/public/prettier-plugin-jsdoc/src/fns/getParsers.js, packages/public/prettier-plugin-jsdoc/src/fns/render.js, packages/public/prettier-plugin-jsdoc/test/e2e/fixtures/random-03.fixture.js, packages/public/prettier-plugin-jsdoc/test/e2e/fixtures/text.fixture.js, packages/public/prettier-plugin-jsdoc/test/unit/fns/getParsers.test.js, packages/public/prettier-plugin-jsdoc/test/unit/fns/render.test.js, yarn.lock
- Updates all the dependencies.
- Add notice about dropping Yarn at the end of the year.
- Insert space between tag name and type if not present.
- Add experimental option to format text blocks without tags.
- Add a section on the `README` on how to validate bugs.
```bash
yarn test
```
=> Fixes and updates

packages/personal/tsconfig/README.md, packages/personal/tsconfig/package.json, packages/personal/tsconfig/tsconfig.base.json, packages/personal/tsconfig/tsconfig.browser.json, packages/personal/tsconfig/tsconfig.node.json, packages/personal/tsconfig/tsconfig.react.json, yarn.lock
I created `@homer0/tsconfig` with my commit `tsconfig.json`s, so I can reuse them in different projects.
Read them :P.
=> Add personal tsconfigs as a package

.github/workflows/test.yml, packages/public/deep-assign/.eslintrc.js, packages/public/deep-assign/.jestrc.js, packages/public/deep-assign/README.md, packages/public/deep-assign/package.json, packages/public/deep-assign/src/deepAssign.ts, packages/public/deep-assign/src/index.ts, packages/public/deep-assign/tests/.eslintrc.js, packages/public/deep-assign/tests/deepAssign.test.ts, packages/public/deep-assign/tests/index.test.ts, packages/public/deep-assign/tests/tsconfig.json, packages/public/deep-assign/tsconfig.json, packages/public/deep-assign/tsup.config.ts, packages/public/object-utils/package.json
It migrates the `DeepAssign` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: deep-assign

.github/workflows/test.yml, packages/public/deep-assign/README.md, packages/public/deferred/.eslintrc.js, packages/public/deferred/.jestrc.js, packages/public/deferred/README.md, packages/public/deferred/package.json, packages/public/deferred/src/index.ts, packages/public/deferred/tests/.eslintrc.js, packages/public/deferred/tests/index.test.ts, packages/public/deferred/tests/tsconfig.json, packages/public/deferred/tsconfig.json, packages/public/deferred/tsup.config.ts, packages/public/extend-promise/README.md, packages/public/jimple/README.md, packages/public/object-utils/README.md, packages/public/prettier-plugin-jsdoc/README.md
It migrates the `deferred` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: deferred

.github/workflows/test.yml, packages/public/deep-assign/package.json, packages/public/deferred/README.md, packages/public/deferred/package.json, packages/public/events-hub/.eslintrc.js, packages/public/events-hub/.jestrc.js, packages/public/events-hub/README.md, packages/public/events-hub/package.json, packages/public/events-hub/src/index.ts, packages/public/events-hub/tests/.eslintrc.js, packages/public/events-hub/tests/index.test.ts, packages/public/events-hub/tests/tsconfig.json, packages/public/events-hub/tsconfig.json, packages/public/events-hub/tsup.config.ts, packages/public/extend-promise/package.json, packages/public/jimple/package.json, packages/public/object-utils/package.json
It migrates the `EventsHub` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: events-hub

.github/workflows/test.yml, package.json, packages/public/api-utils/.eslintrc.js, packages/public/api-utils/.jestrc.js, packages/public/api-utils/README.md, packages/public/api-utils/package.json, packages/public/api-utils/src/apiClient.ts, packages/public/api-utils/src/endpointsGenerator.ts, packages/public/api-utils/src/index.ts, packages/public/api-utils/src/types.ts, packages/public/api-utils/tests/.eslintrc.js, packages/public/api-utils/tests/apiClient.test.ts, packages/public/api-utils/tests/endpointGenerator.test.ts, packages/public/api-utils/tests/jest.setup.js, packages/public/api-utils/tests/tsconfig.json, packages/public/api-utils/tsconfig.json, packages/public/api-utils/tsup.config.ts, packages/public/events-hub/README.md, utils/scripts/build, yarn.lock
It migrates the `APIClient` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: api-utils

.github/workflows/test.yml, packages/public/env-utils/.eslintrc.js, packages/public/env-utils/.jestrc.js, packages/public/env-utils/README.md, packages/public/env-utils/package.json, packages/public/env-utils/src/index.ts, packages/public/env-utils/tests/.eslintrc.js, packages/public/env-utils/tests/index.test.ts, packages/public/env-utils/tests/tsconfig.json, packages/public/env-utils/tsconfig.json, packages/public/env-utils/tsup.config.ts
It migrates the `EnvironmentUtils` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: env-utils

.github/workflows/test.yml, packages/public/package-info/tests/index.test.ts, packages/public/root-file/.eslintrc.js, packages/public/root-file/.jestrc.js, packages/public/root-file/README.md, packages/public/root-file/package.json, packages/public/root-file/src/index.ts, packages/public/root-file/tests/.eslintrc.js, packages/public/root-file/tests/index.test.ts, packages/public/root-file/tests/tsconfig.json, packages/public/root-file/tsconfig.json, packages/public/root-file/tsup.config.ts, utils/scripts/build
It migrates the `rootRequire` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: root-file

.github/workflows/test.yml, README.md, packages/public/simple-storage/.eslintrc.js, packages/public/simple-storage/.jestrc.js, packages/public/simple-storage/README.md, packages/public/simple-storage/package.json, packages/public/simple-storage/src/index.ts, packages/public/simple-storage/src/storage.ts, packages/public/simple-storage/src/types.ts, packages/public/simple-storage/tests/.eslintrc.js, packages/public/simple-storage/tests/storage.test.ts, packages/public/simple-storage/tests/tsconfig.json, packages/public/simple-storage/tsconfig.json, packages/public/simple-storage/tsup.config.ts, utils/scripts/build, yarn.lock
It migrates the `simpleStorage` module from `wootils` into its own package.
```bash
npm test
yarn test
```
=> New package: simple-storage

.github/workflows/test.yml, README.md, packages/public/fs-cache/.eslintrc.js, packages/public/fs-cache/.jestrc.js, packages/public/fs-cache/README.md, packages/public/fs-cache/package.json, packages/public/fs-cache/src/index.ts, packages/public/fs-cache/src/types.ts, packages/public/fs-cache/tests/.eslintrc.js, packages/public/fs-cache/tests/index.test.ts, packages/public/fs-cache/tests/tsconfig.json, packages/public/fs-cache/tsconfig.json, packages/public/fs-cache/tsup.config.ts, packages/public/simple-storage/src/storage.ts, packages/public/simple-storage/src/types.ts, packages/public/simple-storage/tests/storage.test.ts, utils/scripts/build
This one wasn't part of `wootils`, but I had to code it for a small project I was working on, and decided to extend it a little bit, test it, and include it in the monorepo.
```bash
npm test
yarn test
```
=> New package: fs-cache

package.json, packages/personal/eslint-plugin/package.json, packages/personal/tsconfig/package.json, packages/public/api-utils/package.json, packages/public/deep-assign/package.json, packages/public/deferred/package.json, packages/public/env-utils/package.json, packages/public/error-handler/package.json, packages/public/events-hub/package.json, packages/public/extend-promise/package.json, packages/public/fs-cache/package.json, packages/public/fs-cache/tests/index.test.ts, packages/public/jimple/package.json, packages/public/object-utils/package.json, packages/public/package-info/package.json, packages/public/path-utils/package.json, packages/public/prettier-plugin-jsdoc/package.json, packages/public/prettier-plugin-jsdoc/tests/e2e/utils/environment.js, packages/public/root-file/package.json, packages/public/simple-config/package.json, packages/public/simple-logger/package.json, packages/public/simple-storage/package.json, yarn.lock
Updates the dependencies for all the packages, and fixes a couple of issues caused by the update.
```bash
npm test
yarn test
```
=> Update all dependencies

.github/workflows/test.yml, package.json, packages/public/package-info/package.json, utils/scripts/lint-all, utils/scripts/todo
I noticed an ESLint error in one of the packages, and while checking while wasn't it reported before, I found out that the ESLint script wasn't checking TypeScript files ... 🤯🔫.
```bash
yarn test
```
=> Fix ESLint config and add missing dep

package-lock.json, package.json, packages/personal/eslint-plugin/package.json, packages/personal/tsconfig/package.json, packages/public/api-utils/package.json, packages/public/deep-assign/package.json, packages/public/deferred/package.json, packages/public/env-utils/package.json, packages/public/error-handler/package.json, packages/public/events-hub/package.json, packages/public/extend-promise/package.json, packages/public/fs-cache/package.json, packages/public/jimple/package.json, packages/public/object-utils/package.json, packages/public/package-info/package.json, packages/public/path-utils/package.json, packages/public/prettier-plugin-jsdoc/package.json, packages/public/prettier-plugin-jsdoc/src/fns/constants.js, packages/public/prettier-plugin-jsdoc/tests/e2e/fixtures/random-01.fixture.js, packages/public/root-file/package.json, packages/public/simple-config/package.json, packages/public/simple-logger/package.json, packages/public/simple-storage/package.json
- Updates all the dependencies to their latest versions.
- Fixes #64 
```bash
npm test
```
=> fix(prettier-plugin-jsdoc): include 'return' as tag with name as desc

packages/personal/eslint-plugin/presets/next.js, packages/personal/eslint-plugin/presets/typescript.js
Added a new preset generator for the Next's ESLint config.
By having fun :D
=> ESLint plugin: add preset for next

packages/personal/eslint-plugin/rules/node-typescript.js, packages/personal/eslint-plugin/rules/typescript.js
TS will take care of resolving the modules.
```bash
npm test
```
=> fix(eslint-plugin): disable import/no-unresolved for ts

packages/personal/eslint-plugin/configurations/svelte-with-prettier.js, packages/personal/eslint-plugin/index.js
**BREAKING CHANGE**: The ESLint config for Svelte now requires [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte)
```bash
pnpm test
```
=> eslint-plugin: update config for Svelte

package.json, packages/personal/eslint-plugin/package.json, packages/personal/tsconfig/package.json, packages/public/api-utils/package.json, packages/public/deep-assign/package.json, packages/public/deferred/package.json, packages/public/env-utils/package.json, packages/public/error-handler/package.json, packages/public/events-hub/package.json, packages/public/extend-promise/package.json, packages/public/fs-cache/package.json, packages/public/jimple/package.json, packages/public/nestjs-zod-lite/package.json, packages/public/object-utils/package.json, packages/public/package-info/package.json, packages/public/path-utils/package.json, packages/public/react-ssr-config/package.json, packages/public/root-file/package.json, packages/public/simple-config/package.json, packages/public/simple-logger/package.json, packages/public/simple-storage/package.json, packages/public/ts-async-import/package.json, pnpm-lock.yaml
- Updates all dependencies (except ESLint and React).
- Allow for Nest v11 in the Zod plugin
```bash
pnpm test
```
=> Update dependencies and allow Nest v11 in the Zod plugin

.github/workflows/test.yml, README.md, packages/public/routes-manager/.eslintrc.js, packages/public/routes-manager/.jestrc.js, packages/public/routes-manager/README.md, packages/public/routes-manager/package.json, packages/public/routes-manager/src/formatter.ts, packages/public/routes-manager/src/index.ts, packages/public/routes-manager/src/manager.ts, packages/public/routes-manager/src/route.ts, packages/public/routes-manager/src/types.ts, packages/public/routes-manager/tests/.eslintrc.js, packages/public/routes-manager/tests/formatter.test.ts, packages/public/routes-manager/tests/manager.test.ts, packages/public/routes-manager/tests/route.test.ts, packages/public/routes-manager/tests/tsconfig.json, packages/public/routes-manager/tsconfig.json, packages/public/routes-manager/tsup.config.ts, pnpm-lock.yaml
Adds the new package `routes-manager`.
```bash
pnpm test
```
=> Routes manager

packages/personal/eslint-plugin/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Lerna doesn't support `catalog:` yet, so for the moment, I'll avoid using it for prod dependencies. Luckily, only the ESLint plugin has prod deps.
```bash
pnpm test
```
=> Fix ESLint

packages/personal/tsconfig/package.json, pnpm-lock.yaml
Same as #95 ... for `@homer0/tsconfig`.
```bash
pnpm test
```
=> Fix TSConfig

packages/public/nestjs-zod-lite/package.json, packages/public/nestjs-zod-lite/src/dto.ts, packages/public/nestjs-zod-lite/src/exception.ts, packages/public/nestjs-zod-lite/src/pipe.ts, packages/public/nestjs-zod-lite/src/validate.ts, packages/public/nestjs-zod-lite/tests/pipe.test.ts, pnpm-lock.yaml
Updates the code and the peer dependency of the `nestjs-zod-lite` package to use the now released [Zod v4](https://zod.dev/v4).
```bash
pnpm test
```
=> fix(nestjs-zod-lite): migrate to v4
